#!/bin/bash

if [ -n "$CONFIG" ]; then
	echo '^date$|^time$|^tiempo$|^hora$|^temps$|^heure$|^heures$|^datum$|^zeit$'
	exit 0
fi

echo -n "Server time:  "
date
echo -n "Los Angeles:  "
TZ='America/Los_Angeles' date
echo -n "Paris/Madrid: "
TZ='Europe/Madrid' date
echo -n "Lima:         "
TZ='America/Lima' date
echo -n "Melbourne:    "
TZ='Australia/Melbourne' date

#if [ -n "$__reply" ]
#then
#    echo "$__reply"
#else
#    echo 'P O N G'
#fi
