#!/bin/sh -e

if [ -n "$CONFIG" ]; then
	echo '^!?help(!|\?)?$|^ayuda$|^man$|^manual$|^hilfe$|^je suis perdu$|^perdu$|^socorro$|^h$'
	exit 0
fi

echo "Try: ping, pong, cputemp, disks, hn, btc, eth, mn, ddg, web, restart, hello, update, check, \
motd, pick, firewall, backup, totp, date, rss, twitter, tesla, platform, ps, top, alert, users.

Example bot commands provided:

- help: to list available bot commands
- ping: trivial example to have the bot respond
- pong: like ping, but pong
- hello: gives you a friendly compliment
- motd: gives you the Linux Message Of The Day
- ddg: search the web with DuckDuckGo search
- web: surf the web, get a web page (JavaScript not supported)
- rss: read RSS feeds
- twitter: read latest user tweets from Twitter (does not always work as info is scraped from web)
- tesla: chat with your Tesla car (dummy)
- totp: get 2FA Two-factor-authentication TOTP PIN via bot message
- hn: read Hacker News, fetches front page headlines from Hacker News
- mn: read Messari News, fetches the latest news articles from Messari
- date: gives date and time
- btc: gives Bitcoin BTC price info
- eth: gives Ethereum price info
- s2f: print Bitcoin Stock-to-Flow info

Additional bot commands provided to Matrix or system administrators

With these commands a system administrator can maintain his Matrix installation and \
keep a watchful eye on his server all through the Matrix bot. 

- backup: performs backup on server
- users: list registered Matrix users
- disks: see how full your disks or mountpoints are
- cputemp: monitor the CPU temperatures
- restart: restart the bot itself, or Matrix services
- check: check status, health status, updates, etc. of bot, Matrix and the operating system
- update: update operating sytem
- firewall: list the firewall settings and configuration
- date: gives date and time of server
- platform: gives hardware and operating system platform information
- ps: print current CPU, RAM and Disk utilization of server
- top: gives 5 top CPU and RAM consuming processes
- alert: shows if any CPU, RAM, or Disk thresholds have been exceeded (best to combine with a cron job, and have the cron job send the bot message to Matrix admin rooms)"
exit 0

# shellcheck disable=SC2154
if [ -n "$__reply" ]; then
	echo "$__reply"
else
	echo 'Read the config file for help :)'
fi

# EOF
