#!/bin/sh -e

if [ -n "$CONFIG" ]
then
    echo '^!?ping(!|\?)?$' # this regular expressions decides when this bot script is triggered
    exit 0
fi

# the __reply variable is set or can be set in the bot config file
if [ -n "$__reply" ]
then
    echo "$__reply"
else
    echo 'P O N G'
fi
