#!/bin/bash

# PUT YOUR CORRECT ACCESS TOKEN HERE, THIS ACCESS TOKEN MUST HAVE ADMIN RIGHTS
# see documentation how to add admin rights to normal access token
MYACCESSTOKENWITHADMINPERMISSIONS="VERY-LONG-CRYTOGRAHIC-STRING-THAT-IS-YOUR-ACCESS-TOKEN-WITH-ADMIN-PERMISSIONS"
MYHOMESERVER="https://matrix.example.com"


echo "List of at most 100 users:"
curl --silent --header "Authorization: Bearer $MYACCESSTOKENWITHADMINPERMISSIONS" "$MYHOMESERVER/_synapse/admin/v2/users?from=0&limit=100&guests=false" |
        jq '.users[] | .name' | tr -d '"'

